spring:
  application:
    name: spring-cloud-eureka-server

server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    # 自己无需注册自己
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/